laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('para-o-seu-negocio', 'ParaOSeuNegocioController@index')->name('negocio');
    Route::get('o-processo-produtivo', 'ProcessoProdutivoController@index')->name('processo');
    Route::get('nosso-blend', 'NossoBlendController@index')->name('nosso-blend');
    Route::get('onde-encontrar', 'EstabelecimentosController@index')->name('onde-encontrar');
    Route::get('fale-com-a-gente', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');

    Route::group([
        'prefix'     => 'clube-treviolo',
        'middleware' => ['authCliente']
    ], function() {
        Route::get('/', 'ClubeController@index')->name('clube');

        Route::get('graos-treviolo', 'ProdutosController@graos')->name('clube.graos');
        Route::get('insumos-e-acessorios', 'ProdutosController@insumos')->name('clube.insumos');
        Route::get('checkout', 'ProdutosController@checkout')->name('clube.checkout');
        Route::post('adiciona-produto', 'ProdutosController@adiciona');
        Route::post('exclui-produto', 'ProdutosController@exclui');
        Route::post('atualiza-produto', 'ProdutosController@atualiza');
        Route::post('pedido', 'ProdutosController@pedido')->name('clube.pedido');

        Route::get('busca', 'ProdutosController@busca')->name('clube.busca');

        Route::get('maquinas', 'ClubeController@maquinas')->name('clube.maquinas');
        Route::get('maquinas/treinamento', 'ClubeController@treinamento')->name('clube.treinamento');
        Route::get('maquinas/manuais', 'ClubeController@manuais')->name('clube.manuais');
        Route::get('maquinas/orcamento', 'ClubeController@orcamentoMaquinas')->name('clube.orcamentoMaquinas');
        Route::post('maquinas/orcamento', 'ClubeController@orcamentoMaquinasPost')->name('clube.orcamentoMaquinasPost');
        Route::get('maquinas/videos/mais', 'ClubeController@videosMais')->name('clube.videosMais');
        Route::get('maquinas/videos/{video_slug?}', 'ClubeController@videos')->name('clube.videos');
    });
    Route::get('clube-treviolo/login', 'ClubeController@login')->name('clube.login');
    Route::post('clube-treviolo/login', 'ClubeController@loginPost')->name('clube.loginPost');
    Route::get('clube-treviolo/logout', 'ClubeController@logout')->name('clube.logout');

    Route::get('clube-treviolo/cadastro', 'ClubeController@cadastro')->name('clube.cadastro');
    Route::post('clube-treviolo/cadastro', 'ClubeController@cadastroPost')->name('clube.cadastroPost');

    Route::get('clube-treviolo/esqueci', 'ClubeController@esqueci')->name('clube.esqueci');
    Route::post('clube-treviolo/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('clube.redefinir');
    Route::get('clube-treviolo/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('clube-treviolo/reset', 'Auth\PasswordController@reset')->name('clube.reset');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		// Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::resource('videos', 'VideosController');
		Route::resource('treinamento', 'TreinamentoController', ['only' => ['index', 'update']]);
		Route::resource('manuais', 'ManuaisController');
		Route::resource('estabelecimentos', 'EstabelecimentosController');
		Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
		Route::resource('para-o-seu-negocio', 'ParaOSeuNegocioController', ['only' => ['index', 'update']]);
		Route::resource('nosso-blend', 'NossoBlendController', ['only' => ['index', 'update']]);
		Route::resource('processo-produtivo', 'ProcessoProdutivoController', ['only' => ['index', 'update']]);
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('solucoes', 'SolucoesController');
		Route::resource('clientes', 'ClientesController');
		Route::resource('banners', 'BannersController');
		Route::resource('cabecalhos', 'CabecalhosController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::get('orcamentos/produtos/{orcamentos_produtos}/toggle', ['as' => 'painel.orcamentos.produtos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos/produtos', 'OrcamentosController', ['parameters' => ['produtos' => 'orcamentos_produtos']]);

        Route::get('orcamentos/maquinas/{maquinas}/toggle', ['as' => 'painel.orcamentos.maquinas.toggle', 'uses' => 'OrcamentosMaquinasController@toggle']);
        Route::resource('orcamentos/maquinas', 'OrcamentosMaquinasController');

        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Orcamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Orcamento extends Model
{
    protected $table = 'orcamentos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }

    public function cliente()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
}

laravel/app/Http/Controllers/Painel/OrcamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Orcamento;

class OrcamentosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = Orcamento::orderBy('created_at', 'DESC')->get();

        return view('painel.orcamentos.produtos.index', compact('contatosrecebidos'));
    }

    public function show(Orcamento $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.orcamentos.produtos.show', compact('contato'));
    }

    public function destroy(Orcamento $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.orcamentos.produtos.index')->with('success', 'Orçamento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir orçamento: '.$e->getMessage()]);

        }
    }

    public function toggle(Orcamento $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.orcamentos.produtos.index')->with('success', 'Orçamento alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar orçamento: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ProdutosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ProdutosRequest;
use App\Http\Controllers\Controller;

use App\Models\Produto;
use App\Models\ProdutoCategoria;

class ProdutosController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = ProdutoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProdutoCategoria::find($filtro)) {
            $registros = Produto::where('produtos_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = Produto::leftJoin('produtos_categorias as cat', 'cat.id', '=', 'produtos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('produtos.*')
                ->ordenados()->get();
        }

        return view('painel.produtos.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.produtos.create', compact('categorias'));
    }

    public function store(ProdutosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Produto::upload_capa();
            if (isset($input['miniatura'])) $input['miniatura'] = Produto::upload_miniatura();

            Produto::create($input);

            return redirect()->route('painel.produtos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Produto $registro)
    {
        $categorias = $this->categorias;

        return view('painel.produtos.edit', compact('registro', 'categorias'));
    }

    public function update(ProdutosRequest $request, Produto $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Produto::upload_capa();
            if (isset($input['miniatura'])) $input['miniatura'] = Produto::upload_miniatura();

            $registro->update($input);

            return redirect()->route('painel.produtos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Produto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.produtos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Produto;
use App\Models\ProdutoCategoria;

use App\Models\Orcamento;
use App\Models\Contato;

class ProdutosController extends Controller
{
    public function graos()
    {
        $categoria = ProdutoCategoria::whereSlug('graos-treviolo')->first();
        $produtos  = $categoria->produtos;

        return view('frontend.clube.produtos.index', compact('categoria', 'produtos'));
    }

    public function insumos()
    {
        $categoria = ProdutoCategoria::whereSlug('insumos-e-acessorios')->first();
        $produtos  = $categoria->produtos;

        return view('frontend.clube.produtos.index', compact('categoria', 'produtos'));
    }

    public function busca()
    {
        $termo = request('termo');

        if ($termo) {
            $produtos = Produto::ordenados()->busca($termo)->get();

            return view('frontend.clube.produtos.busca', compact('termo', 'produtos'));
        }

        return redirect()->route('clube');
    }

    public function checkout()
    {
        $orcamento = session()->get('orcamento', []);
        $produtos  = Produto::find(array_keys($orcamento));

        $produtos->map(function($produto) use ($orcamento) {
            $produto['quantidade'] = $orcamento[$produto->id];
            return $produto;
        });

        return view('frontend.clube.produtos.checkout', compact('produtos'));
    }

    public function adiciona(Request $request)
    {
        $produto = Produto::find($request->get('id'));

        if (!$produto) {
            return response()->json('Produto não encontrado.', 500);
        }

        $quantidade = (int)$request->get('quantidade');
        $minimo = $produto->quantidade_minima;

        if ($quantidade < $minimo) {
            return response()->json('A quantidade mínima deste produto é '.$minimo.'.', 500);
        }

        try {

            $orcamento = session()->get('orcamento', []);

            if (array_key_exists($produto->id, $orcamento)) {
                $orcamento[$produto->id] += $quantidade;
            } else {
                $orcamento[$produto->id] = $quantidade;
            }

            session()->put('orcamento', $orcamento);

            return response()->json([
                'orcamento' => $orcamento,
                'message'   => 'Produto adicionado com sucesso!'
            ]);

        } catch (\Exception $e) {

            return response()->json('Erro interno do servidor.', 500);

        }
    }

    public function atualiza(Request $request)
    {
        $produto = Produto::find($request->get('id'));

        if (!$produto) {
            return response()->json('Produto não encontrado.', 500);
        }

        try {

            $quantidade = (int)$request->get('quantidade');
            $minimo = $produto->quantidade_minima;

            if ($quantidade < $minimo) {
                return response()->json('A quantidade mínima deste produto é '.$minimo.'.', 500);
            }

            $orcamento = session()->get('orcamento', []);

            if (array_key_exists($produto->id, $orcamento)) {
                $orcamento[$produto->id] = $quantidade;
            }

            session()->put('orcamento', $orcamento);

            return response()->json([
                'message' => 'Orçamento atualizado com sucesso!'
            ]);

        } catch (\Exception $e) {

            return response()->json('Erro interno do servidor.', 500);

        }
    }

    public function exclui(Request $request)
    {
        $produto = Produto::find($request->get('id'));

        if (!$produto) {
            return response()->json('Produto não encontrado.', 500);
        }

        try {

            $orcamento = session()->get('orcamento', []);

            if (array_key_exists($produto->id, $orcamento)) {
                unset($orcamento[$produto->id]);
            }

            session()->put('orcamento', $orcamento);

            return response()->json([
                'message' => 'Produto removido com sucesso!'
            ]);

        } catch (\Exception $e) {

            return response()->json('Erro interno do servidor.', 500);

        }
    }

    public function pedido(Request $request)
    {
        $orcamento = session()->get('orcamento', []);
        $produtos  = Produto::find(array_keys($orcamento));

        $produtos->map(function($produto) use ($orcamento) {
            $produto['quantidade'] = $orcamento[$produto->id];
            return $produto;
        });

        if (!count($produtos)) {
            return redirect()->back();
        }

        $htmlOrcamento = '';
        foreach($produtos as $produto) {
            $htmlOrcamento .= "<p><strong>{$produto->titulo}";
            if ($produto->subtitulo) {
                $htmlOrcamento .= " &middot; {$produto->subtitulo}";
            }
            $htmlOrcamento .= "</strong> - Quantidade: {$produto->quantidade}</p>";
        }

        $orcamento = Orcamento::create([
            'user_id'   => \Auth::user()->id,
            'orcamento' => $htmlOrcamento,
        ]);

        $contato = Contato::first();

        if (isset($contato->email)) {
            \Mail::send('emails.orcamento', compact('orcamento'), function($message) use ($orcamento, $contato)
            {
                $nome = $orcamento->cliente->cadastro === 'pessoa_fisica' ? $orcamento->cliente->nome : $orcamento->cliente->nome_fantasia;

                $message->to($contato->email, config('site.name'))
                        ->subject('[ORÇAMENTO DE PRODUTOS] '.config('site.name'))
                        ->replyTo($orcamento->cliente->email, $nome);
            });
        }

        session()->forget('orcamento');

        return view('frontend.clube.produtos.enviado');
    }
}

laravel/resources/views/painel/orcamentos/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>Orçamentos de produtos</h2>
    </legend>

    @if(!count($contatosrecebidos))
    <div class="alert alert-warning" role="alert">Nenhum orçamento recebido.</div>
    @else
    <table class="table table-striped table-bordered table-hover data-table">
        <thead>
            <tr>
                <th>Data</th>
                <th>Nome/Nome fantasia</th>
                <th>E-mail</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($contatosrecebidos as $contato)

            <tr class="tr-row @if(!$contato->lido) warning @endif">
                <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
                <td>
                    @if($contato->cliente->cadastro === 'pessoa_fisica')
                    {{ $contato->cliente->nome }}
                    @else
                    {{ $contato->cliente->nome_fantasia }}
                    @endif
                </td>
                <td>
                    <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                    {{ $contato->cliente->email }}
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.orcamentos.produtos.destroy', $contato->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.orcamentos.produtos.show', $contato->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                        <a href="{{ route('painel.orcamentos.produtos.toggle', $contato->id) }}" class="btn btn-sm pull-left {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                            <span class="glyphicon small {{ ($contato->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @endif

@stop

laravel/resources/views/painel/orcamentos/produtos/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2>Orçamentos de produtos</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $contato->created_at }}</div>
    </div>

@if($contato->cliente->cadastro === 'pessoa_fisica')
    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->nome : '' }}</div>
    </div>

    <div class="form-group">
        <label>Sobrenome</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->sobrenome : '' }}</div>
    </div>

    <div class="form-group">
        <label>CPF</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->cpf : '' }}</div>
    </div>
@else
    <div class="form-group">
        <label>Razão Social</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->razao_social : '' }}</div>
    </div>

    <div class="form-group">
        <label>Nome Fantasia</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->nome_fantasia : '' }}</div>
    </div>

    <div class="form-group">
        <label>CNPJ</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->cnpj : '' }}</div>
    </div>

    <div class="form-group">
        <label>Inscrição Estadual</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->inscricao_estadual : '' }}</div>
    </div>

    <div class="form-group">
        <label>Responsável</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->responsavel : '' }}</div>
    </div>
@endif

    <div class="form-group">
        <label>Telefone</label>
        <div class="well">{{ $contato->cliente ? $contato->cliente->telefone : '' }}</div>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <div class="well">
            <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->cliente ? $contato->cliente->email : '' }}" style="margin-right:5px;border:0;transition:background .3s">
                <span class="glyphicon glyphicon-copy"></span>
            </button>
            {{ $contato->cliente ? $contato->cliente->email : '' }}
        </div>
    </div>

    <div class="form-group">
        <label>Orçamento</label>
        <div class="well">{!! $contato->orcamento !!}</div>
    </div>

    <a href="{{ route('painel.orcamentos.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop