laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('para-o-seu-negocio', 'ParaOSeuNegocioController@index')->name('negocio');
    Route::get('o-processo-produtivo', 'ProcessoProdutivoController@index')->name('processo');
    Route::get('nosso-blend', 'NossoBlendController@index')->name('nosso-blend');
    Route::get('onde-encontrar', 'EstabelecimentosController@index')->name('onde-encontrar');
    Route::get('fale-com-a-gente', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');

    Route::group([
        'prefix'     => 'clube-treviolo',
        'middleware' => ['authCliente']
    ], function() {
        Route::get('/', 'ClubeController@index')->name('clube');

        Route::get('graos-treviolo', 'ProdutosController@graos')->name('clube.graos');
        Route::get('insumos-e-acessorios', 'ProdutosController@insumos')->name('clube.insumos');
        Route::get('checkout', 'ProdutosController@checkout')->name('clube.checkout');
        Route::post('adiciona-produto', 'ProdutosController@adiciona');
        Route::post('exclui-produto', 'ProdutosController@exclui');
        Route::post('atualiza-produto', 'ProdutosController@atualiza');
        Route::post('pedido', 'ProdutosController@pedido')->name('clube.pedido');

        Route::get('busca', 'ProdutosController@busca')->name('clube.busca');

        Route::get('maquinas', 'ClubeController@maquinas')->name('clube.maquinas');
        Route::get('maquinas/treinamento', 'ClubeController@treinamento')->name('clube.treinamento');
        Route::get('maquinas/manuais', 'ClubeController@manuais')->name('clube.manuais');
        Route::get('maquinas/orcamento', 'ClubeController@orcamentoMaquinas')->name('clube.orcamentoMaquinas');
        Route::post('maquinas/orcamento', 'ClubeController@orcamentoMaquinasPost')->name('clube.orcamentoMaquinasPost');
        Route::get('maquinas/videos/mais', 'ClubeController@videosMais')->name('clube.videosMais');
        Route::get('maquinas/videos/{video_slug?}', 'ClubeController@videos')->name('clube.videos');
    });
    Route::get('clube-treviolo/login', 'ClubeController@login')->name('clube.login');
    Route::post('clube-treviolo/login', 'ClubeController@loginPost')->name('clube.loginPost');
    Route::get('clube-treviolo/logout', 'ClubeController@logout')->name('clube.logout');

    Route::get('clube-treviolo/cadastro', 'ClubeController@cadastro')->name('clube.cadastro');
    Route::post('clube-treviolo/cadastro', 'ClubeController@cadastroPost')->name('clube.cadastroPost');

    Route::get('clube-treviolo/esqueci', 'ClubeController@esqueci')->name('clube.esqueci');
    Route::post('clube-treviolo/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('clube.redefinir');
    Route::get('clube-treviolo/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('clube-treviolo/reset', 'Auth\PasswordController@reset')->name('clube.reset');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		// Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::resource('videos', 'VideosController');
		Route::resource('treinamento', 'TreinamentoController', ['only' => ['index', 'update']]);
		Route::resource('manuais', 'ManuaisController');
		Route::resource('estabelecimentos', 'EstabelecimentosController');
		Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
		Route::resource('para-o-seu-negocio', 'ParaOSeuNegocioController', ['only' => ['index', 'update']]);
		Route::resource('nosso-blend', 'NossoBlendController', ['only' => ['index', 'update']]);
		Route::resource('processo-produtivo', 'ProcessoProdutivoController', ['only' => ['index', 'update']]);
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('solucoes', 'SolucoesController');
		Route::resource('clientes', 'ClientesController');
		Route::resource('banners', 'BannersController');
		Route::resource('cabecalhos', 'CabecalhosController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::get('orcamentos/produtos/{orcamentos_produtos}/toggle', ['as' => 'painel.orcamentos.produtos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos/produtos', 'OrcamentosController', ['parameters' => ['produtos' => 'orcamentos_produtos']]);

        Route::get('orcamentos/maquinas/{maquinas}/toggle', ['as' => 'painel.orcamentos.maquinas.toggle', 'uses' => 'OrcamentosMaquinasController@toggle']);
        Route::resource('orcamentos/maquinas', 'OrcamentosMaquinasController');

        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CabecalhosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CabecalhosRequest;
use App\Http\Controllers\Controller;

use App\Models\Cabecalhos;

class CabecalhosController extends Controller
{
    public function index()
    {
        $registro = Cabecalhos::first();

        return view('painel.cabecalhos.edit', compact('registro'));
    }

    public function update(CabecalhosRequest $request, Cabecalhos $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['sobre'])) $input['sobre'] = Cabecalhos::upload_sobre();
            if (isset($input['para_o_seu_negocio'])) $input['para_o_seu_negocio'] = Cabecalhos::upload_para_o_seu_negocio();
            if (isset($input['processo_produtivo'])) $input['processo_produtivo'] = Cabecalhos::upload_processo_produtivo();
            if (isset($input['nosso_blend'])) $input['nosso_blend'] = Cabecalhos::upload_nosso_blend();
            if (isset($input['onde_encontrar'])) $input['onde_encontrar'] = Cabecalhos::upload_onde_encontrar();
            if (isset($input['contato'])) $input['contato'] = Cabecalhos::upload_contato();

            $registro->update($input);

            return redirect()->route('painel.cabecalhos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $registros = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.clientes.create');
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();

            Cliente::create($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Cliente $registro)
    {
        return view('painel.clientes.edit', compact('registro'));
    }

    public function update(ClientesRequest $request, Cliente $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Cliente $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EstabelecimentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EstabelecimentosRequest;
use App\Http\Controllers\Controller;

use App\Models\Estabelecimento;

class EstabelecimentosController extends Controller
{
    public function index()
    {
        $registros = Estabelecimento::orderBy('id', 'DESC')->get();

        return view('painel.estabelecimentos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.estabelecimentos.create');
    }

    public function store(EstabelecimentosRequest $request)
    {
        try {

            $input = $request->all();

            Estabelecimento::create($input);

            return redirect()->route('painel.estabelecimentos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Estabelecimento $registro)
    {
        return view('painel.estabelecimentos.edit', compact('registro'));
    }

    public function update(EstabelecimentosRequest $request, Estabelecimento $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.estabelecimentos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Estabelecimento $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.estabelecimentos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\HomeRequest;
use App\Http\Controllers\Controller;

use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.cabecalhos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.cabecalhos.index') }}">Cabeçalhos</a>
    </li>
    <li class="dropdown @if(str_is('painel.home*', Route::currentRouteName()) || str_is('painel.banners*', Route::currentRouteName()) || str_is('painel.solucoes*', Route::currentRouteName()) || str_is('painel.clientes*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Textos</a>
            </li>
            <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
            <li @if(str_is('painel.solucoes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.solucoes.index') }}">Soluções</a>
            </li>
            <li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.clientes.index') }}">Clientes</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.sobre*', Route::currentRouteName()) || str_is('painel.para-o-seu-negocio*', Route::currentRouteName()) || str_is('painel.processo-produtivo*', Route::currentRouteName()) || str_is('painel.nosso-blend*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Páginas
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.sobre*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.sobre.index') }}">Sobre</a>
            </li>
        	<li @if(str_is('painel.para-o-seu-negocio*', Route::currentRouteName())) class="active" @endif>
        		<a href="{{ route('painel.para-o-seu-negocio.index') }}">Para o seu negócio</a>
        	</li>
            <li @if(str_is('painel.processo-produtivo*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.processo-produtivo.index') }}">Processo Produtivo</a>
            </li>
            <li @if(str_is('painel.nosso-blend*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.nosso-blend.index') }}">Nosso Blend</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.estabelecimentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.estabelecimentos.index') }}">Estabelecimentos</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.produtos*', Route::currentRouteName()) || str_is('painel.manuais*', Route::currentRouteName()) || str_is('painel.treinamento*', Route::currentRouteName()) || str_is('painel.videos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Clube Treviolo
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.produtos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.produtos.index') }}">Produtos</a>
            </li>
            <li @if(str_is('painel.manuais*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.manuais.index') }}">Manuais</a>
            </li>
            <li @if(str_is('painel.treinamento*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.treinamento.index') }}">Treinamento</a>
            </li>
            <li @if(str_is('painel.videos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.videos.index') }}">Vídeos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.orcamentos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Orçamentos
            @if($maquinasNaoLidos >= 1 || $produtosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $maquinasNaoLidos + $produtosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.orcamentos.produtos.index') }}">
                Produtos
                @if($produtosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $produtosNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.orcamentos.maquinas.index') }}">
                Máquinas
                @if($maquinasNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $maquinasNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>